### ISSUE TITLE
Filter By UI ID

### ISSUE THREAD

**Issue by hayrullahmete** [code4me/4me-sdk-graphql-dotnet#15]
Hi,
Is it possible to filter any object by UI id?

![image](https://github.com/user-attachments/assets/a4117426-8ceb-4681-965a-442ddece0fc8)

![image](https://github.com/user-attachments/assets/666d972d-3fdd-4617-8787-e61beaa72dd1)

**Comment by klaasvandeweerdt** [comment]
@hayrullahmete, Certain objects, like requests and tasks, support UI ID filters. The `FreeFormatFilter` returns the same results as the UI filter, which does not work with IDs.
```csharp
var teams = await client.Get(new TeamQuery().FreeFormatFilter("Application Development"));
```
![image](https://github.com/user-attachments/assets/c6a9fab4-e91f-4bed-b610-40af5f61c8d0)

You can construct a GraphQL ID from the UI ID by creating a base64 string. If you decode a GraphQL ID, you'll notice it includes the UI ID. This approach is not document by Xurrent because it is subject to change. While it's unlikely, it could potentially be updated in the future.

The `Xurrent.GraphQL` NuGet package is now available and is set to replace the `Sdk4me.GraphQL` package in the future.

**Comment by hayrullahmete** [comment]
Ok, I got it. I was able to achieve success as follows. I am providing the sample code as an example. Thank you for support.


```
            string text = $"4me.com/Team/{id}";
            byte[] textBytes = System.Text.Encoding.UTF8.GetBytes(text);
            string base64 = Convert.ToBase64String(textBytes);

            Sdk4me.GraphQL.AuthenticationToken token = new Sdk4me.GraphQL.AuthenticationToken(authToken);
            Sdk4meClient client = new(token, accountID, environmentType, EnvironmentRegion.EU);
            client.MaximumQueryDepthLevelConnections = 13;
            TeamQuery objectQuery = new TeamQuery()
                .Filter("id", FilterOperator.Equals, base64)
                .Select(TeamField.ID, TeamField.Name, TeamField.Disabled, TeamField.CustomFields);
```
